# Generated by Django 5.1.4 on 2025-07-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
