# Generated by Django 5.1.4 on 2025-07-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0003_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
