# Generated by Django 5.1.4 on 2025-05-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0003_package_description_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='True', max_length=20),
        ),
    ]
