# Generated by Django 5.1.4 on 2025-07-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0005_alter_order_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSupportRequest',
        ),
    ]
