# Generated by Django 5.1.4 on 2025-07-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0006_remove_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
