# Generated by Django 5.1.4 on 2025-07-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0006_delete_paymentsupportrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Packages.order')),
                ('transaction_id', models.CharField(max_length=100)),
            ],
            bases=('Packages.order',),
        ),
    ]
