# Generated by Django 5.1.4 on 2025-07-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0007_transactiondetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionDetails',
            new_name='TransactionDetail',
        ),
    ]
