# Generated by Django 5.1.4 on 2025-07-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0007_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
    ]
